server:
  servlet:
    context-path: /api
  port: 8080
  ssl:
    enabled: false

OPENVIDU_URL: http://43.200.169.6:8080/
OPENVIDU_SECRET: MY_SECRET


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/anudar?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    # 개인 노트북 실행시 추가하는 코드
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect


jwt:
  secret: ssafyprojectanudarexhibitionjwtsecretkeyssafyprojectanudarexhibitionjwtsecretkey
  access-token:
    expiretime: 3600000

cloud:
  aws:
    s3:
      bucket: anudar-img
      folder:
        folderName1: user/
        folderName2: exhibit/
    credentials:
      access-key: AKIA3YP4ZZRHKG3CAJ2Y
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

